begin SENSOR_GLOBAL
    external_platform_library_path = libsensor_platform_broadcom_rpi5.so
    external_platform_library_variant = PLATFORM_VARIANT_BCM2712
end SENSOR_GLOBAL

begin SENSOR_UNIT_1
    type = file_camera
    address = /data/share/sensor/simulator_camera.mov
end SENSOR_UNIT_1
