begin SENSOR_UNIT_1
    type = simulator_camera
    name = front
    position = 0, 0, 0
    direction = 0, 0, 0
    default_video_resolution = 1280, 720
    default_video_format = ycbycr
    num_user_buffers = 4
end SENSOR_UNIT_1
