#!/bin/bash
#
# Copyright (c) 2026, BlackBerry Limited. All rights reserved.
# limitations under the License.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and

snippet_path=$1
apk_root=$2
repo_parent=$3
prefix=$4
target_partition_prefix=$5

touch $snippet_path

while IFS= read -r -d '' file_abs; do
    perm=$(stat --format='%a' "$file_abs")
    uid=$(stat --format='%u' "$file_abs")
    gid=$(stat --format='%g' "$file_abs")

    # First strip it relative to $root
    file=${file_abs#"$apk_root/"}
    # mki_repo_path needs to be appended by $repo_parent
    mki_repo_path="$repo_parent"/"$file"
    if [[ "$mki_repo_path" == *" "* ]]; then
        mki_repo_path='"$mki_repo_path"'
    fi
    # target_partition_path need to be stripped of the prefix first, then appended by
    # $target_partition_prefix
    target_partition_path=${file#"$prefix/"}
    if [[ $target_partition_prefix != "" ]]; then
        target_partition_path="$target_partition_prefix"/"$target_partition_path"
    fi
    if [[ "$target_partition_path" == *" "* ]]; then
        target_partition_path='"$target_partition_path"'
    fi

    if [[ -d $file_abs ]] && ! [[ -h $file_abs ]]; then
        echo "[type=dir uid=$uid gid=$gid dperms=$perm] $target_partition_path" >> $snippet_path
    elif [[ -h $file_abs ]]; then
        linkto=$(readlink "$file_abs")
        echo "[type=link uid=$uid gid=$gid] $target_partition_path=$linkto" >> $snippet_path
    else
        echo "[type=file uid=$uid gid=$gid perms=$perm] $target_partition_path=$mki_repo_path" >> $snippet_path
    fi
done < <(find "$apk_root"/"$prefix" -mindepth 1 -print0)

exit 0
