[styling=Python]

[keywords]
primary=and break continue elif else endforeach endif false foreach if in not or true
identifiers=add_global_arguments add_global_link_arguments add_languages add_project_arguments add_project_link_arguments add_test_setup alias_target assert benchmark both_libraries build_target configuration_data configure_file custom_target declare_dependency dependency disabler environment error executable files find_library find_program generator get_option get_variable import include_directories install_data install_headers install_man install_subdir is_disabler is_variable jar join_paths library message option project run_command run_target set_variable shared_library shared_module static_library subdir subdir_done subproject summary test vcs_tag warning

[lexer_properties=Python]

[settings]
lexer_filetype=Python
tag_parser=Meson
extension=build
comment_single=#
mime_type=text/x-meson

[indentation]
#width=4
# 0 is spaces, 1 is tabs, 2 is tab & spaces
#type=1

[build-menu]
FT_00_LB=Setup Build
FT_00_CM=meson setup -Dprefix=/usr --wipe build
FT_00_BD=false
FT_01_LB=Build
FT_01_CM=ninja -C build
FT_01_BD=false
EX_00_LB=Install
EX_00_CM=sudo ninja -C build install
EX_00_BD=false

